name       : eternal-terminal
version    : 6.2.4
release    : 3
source     :
    - https://github.com/MisterTea/EternalTerminal/archive/refs/tags/et-v6.2.4.tar.gz : 95cfb79bc2f25d19eb84ca3c28dba860bb52b3750334d373adeb2cd061de6ba6
license    : Apache-2.0
homepage   : https://eternalterminal.dev
component  : network.clients
summary    : Remote shell that automatically reconnects without interrupting the session.
description: |
    Eternal Terminal is a remote shell that automatically reconnects without interrupting the session. It also supports scrollback.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libsodium)
    - pkgconfig(protobuf)
    - extra-cmake-modules
    - libboost-devel
setup      : |
    %cmake -DDISABLE_VCPKG=on
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 etc/et.cfg $installdir/etc/et.cfg
    install -Dm00644 systemctl/et.service $installdir/etc/systemd/system/et.service
    # Enable service by default
    install -dm00755 $installdir/etc/systemd/system/multi-user.target.wants
    ln -sv /etc/systemd/system/et.service $installdir/etc/systemd/system/multi-user.target.wants
